### ISSUE TITLE
1.3版本如何正常使用

### ISSUE THREAD

**Issue by PhamtomK12** [MartinKayJr/AutoCheckinPlugin#1]
![Screenshot_20230911-012128](https://github.com/MartinKayJr/AutoCheckinPlugin/assets/85309931/01786873-8a57-4905-87b5-6262b26d42ba)
![Screenshot_20230911-012404](https://github.com/MartinKayJr/AutoCheckinPlugin/assets/85309931/98590109-a1ab-4e80-bdae-fa53af7e766b)

已赋予root权限 且已允许获取已安装应用权限 但是好像检索不到企业微信(4.1.8) 

还有定时打卡时间选项也有BUG

**Comment by PhamtomK12** [comment]
系统版本 安卓13 类原生
root 方案为 kernelsu

**Comment by PhamtomK12** [comment]
系统版本 安卓13 类原生
root 方案为 kernelsu

**Comment by MartinKayJr** [comment]
1.上面4个选项全部要勾选
2.取消锁屏
3.WIFI连接上
4.企业微信的版本有所要求，8.0.40，2402。
5.打卡时间还没更新
6.目前只支持周一到周六，建议阅读代码来完善自己的。
7.时间不需要勾选，只需要选择好时间后，勾选自动打卡
